M48
; DRILL file {KiCad 9.0.0} date 2025-03-04T12:57:17-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-04T12:57:17-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X165.608Y-124.668
T2
X165.608Y-117.178
T3
X108.204Y-126.492
X114.554Y-81.534
X227.86Y-129.032
M30
